remote_theme: fongandrew/hydeout
title: The Big Picture by Evangelos Kassos
description: Welcome to my Election Analytics Blog as we embarg on this unbredictable eletion campaign, amidst the COVID-19 pandemic. Some will win, some will lose, but, hopefully, democracy wins at the end! Updates published weekly on Monday nights.
