theme: jekyll-theme-cayman
title: The Big Picture
description: Welcome to my Election Analytics Blog as we embark on this unpredictable election campaign, amidst the COVID-19 pandemic. Some will win, some will lose, but, hopefully, democracy wins at the end! Updates published weekly on Monday nights.
